# Get List
GET http://[::]:3000/products?_start=0&_limit=5 HTTP/1.1

###

# Get By Id
GET http://[::]:3000/products/1 HTTP/1.1

###

# Create
POST http://[::]:3000/products HTTP/1.1
Content-Type: application/json

{
  "name": "書籍 B",
  "authors": ["作者甲", "作者乙", "作者丙"],
  "company": "博碩文化",
  "isShow": true,
  "imgUrl": "https://api.fnkr.net/testimg/200x200/DDDDDD/999999/?text=img",
  "createDate": "2023-10-17T00:00:00.000+08:00",
  "price": 10000
}

###

# Update
PUT http://[::]:3000/products/2 HTTP/1.1
Content-Type: application/json

{
  "name": "書籍 B",
  "authors": [
    "作者甲",
    "作者乙",
    "作者丙"
  ],
  "company": "博碩文化",
  "isShow": false,
  "imgUrl": "https://api.fnkr.net/testimg/200x200/DDDDDD/999999/?text=img",
  "createDate": "2023-10-17T00:00:00.000+08:00",
  "price": 10000
}

###

# Delete
DELETE http://[::]:3000/products/2 HTTP/1.1
